CREATE TABLE ITEM (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    RARIDADE VARCHAR2(50) NOT NULL,
    PRECO NUMBER(10, 2) NOT NULL,
    DONO_ID NUMBER NOT NULL,
    CONSTRAINT FK_ITEM_PERSONAGEM FOREIGN KEY (DONO_ID) REFERENCES PERSONAGEM(ID)
);
